# Generated by Django 6.0.7 on 2026-07-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='cpen',
            field=models.URLField(blank=True, null=True),
        ),
    ]
