# Generated by Django 6.0.7 on 2026-07-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_rename_name_about_first_name_about_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
