# Generated by Django 6.0.7 on 2026-07-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_workexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
