# Generated by Django 6.0.7 on 2026-07-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0006_workexperience_present'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('start_month', models.CharField(max_length=20)),
                ('start_year', models.IntegerField()),
                ('end_month', models.CharField(max_length=20)),
                ('end_year', models.IntegerField()),
                ('present', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='start_date',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='end_month',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workexperience',
            name='end_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='start_month',
            field=models.CharField(default='Jan', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workexperience',
            name='start_year',
            field=models.IntegerField(default=0),
        ),
    ]
