# Generated by Django 6.0.7 on 2026-07-18 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0009_alter_certification_month_alter_education_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoulunteerDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_duties', to='builder.volunteer')),
            ],
        ),
    ]
