# Generated by Django 6.0.7 on 2026-07-20 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0011_resume_jobduty_resume_skill_resume_volunteer_resume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
    ]
