# Generated by Django 6.0.7 on 2026-07-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0012_remove_about_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='resume',
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='resumes', to='builder.skill'),
        ),
    ]
