# Generated by Django 6.0.7 on 2026-07-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0013_remove_skill_resume_resume_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobduty',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='voulunteerduty',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='resume',
        ),
        migrations.AddField(
            model_name='resume',
            name='certifications',
            field=models.ManyToManyField(blank=True, related_name='resumes', to='builder.certification'),
        ),
        migrations.AddField(
            model_name='resume',
            name='jobs',
            field=models.ManyToManyField(blank=True, related_name='resumes', to='builder.workexperience'),
        ),
        migrations.AddField(
            model_name='resume',
            name='volunteer_experiences',
            field=models.ManyToManyField(blank=True, related_name='resumes', to='builder.volunteer'),
        ),
    ]
