# Generated by Django 6.0.7 on 2026-07-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0014_remove_jobduty_resume_remove_volunteer_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='certifications',
            field=models.ManyToManyField(blank=True, related_name='certifications', to='builder.certification'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='jobs',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='builder.workexperience'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='skills', to='builder.skill'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='volunteer_experiences',
            field=models.ManyToManyField(blank=True, related_name='volunteer_experiences', to='builder.volunteer'),
        ),
    ]
