# Generated by Django 6.0.7 on 2026-07-20 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0015_alter_resume_certifications_alter_resume_jobs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='summary',
        ),
    ]
