# Generated by Django 6.0.7 on 2026-07-20 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0016_remove_about_summary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Profile',
        ),
    ]
